/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CommonModule"
 * 	found in "CommonModule.asn1"
 */

#include "BinaryData.h"

static asn_TYPE_member_t asn_MBR_BinaryData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BinaryData, choice.bitString),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"bitString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BinaryData, choice.octetString),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OctetString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"octetString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BinaryData, choice.hexString),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HexString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hexString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BinaryData, choice.base64String),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Base64String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"base64String"
		},
};
static asn_TYPE_tag2member_t asn_MAP_BinaryData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* bitString at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* octetString at 39 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* hexString at 40 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* base64String at 42 */
};
static asn_CHOICE_specifics_t asn_SPC_BinaryData_specs_1 = {
	sizeof(struct BinaryData),
	offsetof(struct BinaryData, _asn_ctx),
	offsetof(struct BinaryData, present),
	sizeof(((struct BinaryData *)0)->present),
	asn_MAP_BinaryData_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_BinaryData = {
	"BinaryData",
	"BinaryData",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_BinaryData_1,
	4,	/* Elements count */
	&asn_SPC_BinaryData_specs_1	/* Additional specs */
};

