/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "BootloaderModule"
 * 	found in "BootloaderModule.asn1"
 */

#ifndef	_ECUVersionManifest_H_
#define	_ECUVersionManifest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ECUVersionManifestSigned.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECUVersionManifest */
typedef struct ECUVersionManifest {
	ECUVersionManifestSigned_t	 Signed;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECUVersionManifest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECUVersionManifest;

#ifdef __cplusplus
}
#endif

#endif	/* _ECUVersionManifest_H_ */
#include <asn_internal.h>
