/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CommonModule"
 * 	found in "CommonModule.asn1"
 */

#ifndef	_HexString_H_
#define	_HexString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HexString */
typedef VisibleString_t	 HexString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HexString;
asn_struct_free_f HexString_free;
asn_struct_print_f HexString_print;
asn_constr_check_f HexString_constraint;
ber_type_decoder_f HexString_decode_ber;
der_type_encoder_f HexString_encode_der;
xer_type_decoder_f HexString_decode_xer;
xer_type_encoder_f HexString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HexString_H_ */
#include <asn_internal.h>
