/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#include "Nonces.h"

static asn_TYPE_member_t asn_MBR_Nonces_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_Nonce,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_Nonces_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_Nonces_specs_1 = {
	sizeof(struct Nonces),
	offsetof(struct Nonces, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_Nonces = {
	"Nonces",
	"Nonces",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Nonces_tags_1,
	sizeof(asn_DEF_Nonces_tags_1)
		/sizeof(asn_DEF_Nonces_tags_1[0]), /* 1 */
	asn_DEF_Nonces_tags_1,	/* Same as above */
	sizeof(asn_DEF_Nonces_tags_1)
		/sizeof(asn_DEF_Nonces_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Nonces_1,
	1,	/* Single element */
	&asn_SPC_Nonces_specs_1	/* Additional specs */
};

