/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Natural;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfNonces;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfCurrentTimes;
extern struct asn_TYPE_descriptor_s asn_DEF_ImageRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_VersionReport;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleVersionManifest;
extern struct asn_TYPE_descriptor_s asn_DEF_MetadataBroadcast;
extern struct asn_TYPE_descriptor_s asn_DEF_MetadataFile;
extern struct asn_TYPE_descriptor_s asn_DEF_ImageFile;
extern struct asn_TYPE_descriptor_s asn_DEF_ImageBlock;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CommonModule in CommonModule.asn1 */
	&asn_DEF_Natural,	
	/* From module TimeServerModule in TimeServerModule.asn1 */
	&asn_DEF_SequenceOfNonces,	
	&asn_DEF_SequenceOfCurrentTimes,	
	/* From module BootloaderModule in BootloaderModule.asn1 */
	&asn_DEF_ImageRequest,	
	&asn_DEF_VersionReport,	
	/* From module ApplicationModule in ApplicationModule.asn1 */
	&asn_DEF_VehicleVersionManifest,	
	&asn_DEF_MetadataBroadcast,	
	&asn_DEF_MetadataFile,	
	&asn_DEF_ImageFile,	
	&asn_DEF_ImageBlock,	
	0
};

