/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationModule"
 * 	found in "ApplicationModule.asn1"
 */

#ifndef	_VehicleVersionManifest_H_
#define	_VehicleVersionManifest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleVersionManifestSigned.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleVersionManifest */
typedef struct VehicleVersionManifest {
	VehicleVersionManifestSigned_t	 Signed;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleVersionManifest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleVersionManifest;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleVersionManifest_H_ */
#include <asn_internal.h>
