/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#include "Custom.h"

static asn_TYPE_member_t asn_MBR_Custom_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, ecuIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ecuIdentifier"
		},
	{ ATF_POINTER, 2, offsetof(struct Custom, encryptedTarget),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Target,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptedTarget"
		},
	{ ATF_POINTER, 1, offsetof(struct Custom, encryptedSymmetricKey),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EncryptedSymmetricKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptedSymmetricKey"
		},
};
static ber_tlv_tag_t asn_DEF_Custom_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Custom_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecuIdentifier at 33 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* encryptedTarget at 36 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* encryptedSymmetricKey at 39 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Custom_specs_1 = {
	sizeof(struct Custom),
	offsetof(struct Custom, _asn_ctx),
	asn_MAP_Custom_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Custom = {
	"Custom",
	"Custom",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Custom_tags_1,
	sizeof(asn_DEF_Custom_tags_1)
		/sizeof(asn_DEF_Custom_tags_1[0]), /* 1 */
	asn_DEF_Custom_tags_1,	/* Same as above */
	sizeof(asn_DEF_Custom_tags_1)
		/sizeof(asn_DEF_Custom_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Custom_1,
	3,	/* Elements count */
	&asn_SPC_Custom_specs_1	/* Additional specs */
};

