/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "ApplicationModule"
 * 	found in "ApplicationModule.asn1"
 */

#ifndef	_ImageBlock_H_
#define	_ImageBlock_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Filename.h"
#include "Positive.h"
#include "BinaryData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ImageBlock */
typedef struct ImageBlock {
	Filename_t	 filename;
	Positive_t	 blockNumber;
	BinaryData_t	 block;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImageBlock_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImageBlock;

#ifdef __cplusplus
}
#endif

#endif	/* _ImageBlock_H_ */
#include <asn_internal.h>
