/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "BootloaderModule"
 * 	found in "BootloaderModule.asn1"
 */

#ifndef	_ImageRequest_H_
#define	_ImageRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Filename.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ImageRequest */
typedef struct ImageRequest {
	Filename_t	 filename;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImageRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImageRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ImageRequest_H_ */
#include <asn_internal.h>
