/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#ifndef	_RoleName_H_
#define	_RoleName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StrictFilename.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RoleName */
typedef StrictFilename_t	 RoleName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoleName;
asn_struct_free_f RoleName_free;
asn_struct_print_f RoleName_print;
asn_constr_check_f RoleName_constraint;
ber_type_decoder_f RoleName_decode_ber;
der_type_encoder_f RoleName_encode_der;
xer_type_decoder_f RoleName_decode_xer;
xer_type_encoder_f RoleName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RoleName_H_ */
#include <asn_internal.h>
