/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimestampModule"
 * 	found in "TimestampModule.asn1"
 */

#include "TimestampMetadata.h"

static asn_TYPE_member_t asn_MBR_TimestampMetadata_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimestampMetadata, filename),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Filename,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"filename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimestampMetadata, version),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Version,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
};
static ber_tlv_tag_t asn_DEF_TimestampMetadata_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TimestampMetadata_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* filename at 8 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* version at 9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TimestampMetadata_specs_1 = {
	sizeof(struct TimestampMetadata),
	offsetof(struct TimestampMetadata, _asn_ctx),
	asn_MAP_TimestampMetadata_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TimestampMetadata = {
	"TimestampMetadata",
	"TimestampMetadata",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TimestampMetadata_tags_1,
	sizeof(asn_DEF_TimestampMetadata_tags_1)
		/sizeof(asn_DEF_TimestampMetadata_tags_1[0]), /* 1 */
	asn_DEF_TimestampMetadata_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimestampMetadata_tags_1)
		/sizeof(asn_DEF_TimestampMetadata_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TimestampMetadata_1,
	2,	/* Elements count */
	&asn_SPC_TimestampMetadata_specs_1	/* Additional specs */
};

