/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CommonModule"
 * 	found in "CommonModule.asn1"
 */

#ifndef	_BinaryData_H_
#define	_BinaryData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BitString.h"
#include "OctetString.h"
#include "HexString.h"
#include "Base64String.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BinaryData_PR {
	BinaryData_PR_NOTHING,	/* No components present */
	BinaryData_PR_bitString,
	BinaryData_PR_octetString,
	BinaryData_PR_hexString,
	BinaryData_PR_base64String
} BinaryData_PR;

/* BinaryData */
typedef struct BinaryData {
	BinaryData_PR present;
	union BinaryData_u {
		BitString_t	 bitString;
		OctetString_t	 octetString;
		HexString_t	 hexString;
		Base64String_t	 base64String;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BinaryData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BinaryData;

#ifdef __cplusplus
}
#endif

#endif	/* _BinaryData_H_ */
#include <asn_internal.h>
