/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#ifndef	_CurrentTime_H_
#define	_CurrentTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NonceAndTimestamp.h"
#include "Length.h"
#include "Signatures.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CurrentTime */
typedef struct CurrentTime {
	NonceAndTimestamp_t	 Signed;
	Length_t	 numberOfSignatures;
	Signatures_t	 signatures;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurrentTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurrentTime;

#ifdef __cplusplus
}
#endif

#endif	/* _CurrentTime_H_ */
#include <asn_internal.h>
