/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#include "CurrentTime.h"

static asn_TYPE_member_t asn_MBR_CurrentTime_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentTime, Signed),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NonceAndTimestamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentTime, numberOfSignatures),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Length,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfSignatures"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentTime, signatures),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Signatures,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signatures"
		},
};
static ber_tlv_tag_t asn_DEF_CurrentTime_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CurrentTime_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* signed at 24 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfSignatures at 25 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* signatures at 27 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CurrentTime_specs_1 = {
	sizeof(struct CurrentTime),
	offsetof(struct CurrentTime, _asn_ctx),
	asn_MAP_CurrentTime_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CurrentTime = {
	"CurrentTime",
	"CurrentTime",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CurrentTime_tags_1,
	sizeof(asn_DEF_CurrentTime_tags_1)
		/sizeof(asn_DEF_CurrentTime_tags_1[0]), /* 1 */
	asn_DEF_CurrentTime_tags_1,	/* Same as above */
	sizeof(asn_DEF_CurrentTime_tags_1)
		/sizeof(asn_DEF_CurrentTime_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CurrentTime_1,
	3,	/* Elements count */
	&asn_SPC_CurrentTime_specs_1	/* Additional specs */
};

