/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#ifndef	_DelegatedTargetsRole_H_
#define	_DelegatedTargetsRole_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RoleName.h"
#include "StrictFilename.h"
#include "Length.h"
#include "Keyids.h"
#include "Threshold.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DelegatedTargetsRole */
typedef struct DelegatedTargetsRole {
	RoleName_t	 rolename;
	StrictFilename_t	*filename	/* OPTIONAL */;
	Length_t	 numberOfKeyids;
	Keyids_t	 keyids;
	Threshold_t	 threshold;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DelegatedTargetsRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DelegatedTargetsRole;

#ifdef __cplusplus
}
#endif

#endif	/* _DelegatedTargetsRole_H_ */
#include <asn_internal.h>
