/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#ifndef	_EncryptedSymmetricKeyType_H_
#define	_EncryptedSymmetricKeyType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EncryptedSymmetricKeyType {
	EncryptedSymmetricKeyType_aes128	= 0,
	EncryptedSymmetricKeyType_aes192	= 1,
	EncryptedSymmetricKeyType_aes256	= 2
	/*
	 * Enumeration is extensible
	 */
} e_EncryptedSymmetricKeyType;

/* EncryptedSymmetricKeyType */
typedef ENUMERATED_t	 EncryptedSymmetricKeyType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedSymmetricKeyType;
asn_struct_free_f EncryptedSymmetricKeyType_free;
asn_struct_print_f EncryptedSymmetricKeyType_print;
asn_constr_check_f EncryptedSymmetricKeyType_constraint;
ber_type_decoder_f EncryptedSymmetricKeyType_decode_ber;
der_type_encoder_f EncryptedSymmetricKeyType_encode_der;
xer_type_decoder_f EncryptedSymmetricKeyType_decode_xer;
xer_type_encoder_f EncryptedSymmetricKeyType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptedSymmetricKeyType_H_ */
#include <asn_internal.h>
