/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#ifndef	_Nonces_H_
#define	_Nonces_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Nonce.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Nonces */
typedef struct Nonces {
	A_SEQUENCE_OF(Nonce_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Nonces_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Nonces;

#ifdef __cplusplus
}
#endif

#endif	/* _Nonces_H_ */
#include <asn_internal.h>
