/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#include "NonceAndTimestamp.h"

static asn_TYPE_member_t asn_MBR_NonceAndTimestamp_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NonceAndTimestamp, nonce),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Nonce,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nonce"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NonceAndTimestamp, timestamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTCDateTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timestamp"
		},
};
static ber_tlv_tag_t asn_DEF_NonceAndTimestamp_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_NonceAndTimestamp_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nonce at 29 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* timestamp at 30 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NonceAndTimestamp_specs_1 = {
	sizeof(struct NonceAndTimestamp),
	offsetof(struct NonceAndTimestamp, _asn_ctx),
	asn_MAP_NonceAndTimestamp_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NonceAndTimestamp = {
	"NonceAndTimestamp",
	"NonceAndTimestamp",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NonceAndTimestamp_tags_1,
	sizeof(asn_DEF_NonceAndTimestamp_tags_1)
		/sizeof(asn_DEF_NonceAndTimestamp_tags_1[0]), /* 1 */
	asn_DEF_NonceAndTimestamp_tags_1,	/* Same as above */
	sizeof(asn_DEF_NonceAndTimestamp_tags_1)
		/sizeof(asn_DEF_NonceAndTimestamp_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_NonceAndTimestamp_1,
	2,	/* Elements count */
	&asn_SPC_NonceAndTimestamp_specs_1	/* Additional specs */
};

