/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Natural;
extern struct asn_TYPE_descriptor_s asn_DEF_Metadata;
extern struct asn_TYPE_descriptor_s asn_DEF_TrustPinning;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CommonModule in CommonModule.asn1 */
	&asn_DEF_Natural,	
	/* From module MetadataModule in MetadataModule.asn1 */
	&asn_DEF_Metadata,	
	/* From module TrustPinningModule in TrustPinningModule.asn1 */
	&asn_DEF_TrustPinning,	
	0
};

