/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TrustPinningModule"
 * 	found in "TrustPinningModule.asn1"
 */

#ifndef	_RepositoryDelegation_H_
#define	_RepositoryDelegation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Length.h"
#include "Paths.h"
#include "RepositoryNames.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RepositoryDelegation */
typedef struct RepositoryDelegation {
	Length_t	 numberOfPaths;
	Paths_t	 paths;
	Length_t	 numberOfRepositories;
	RepositoryNames_t	 repositories;
	BOOLEAN_t	*terminating	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RepositoryDelegation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RepositoryDelegation;

#ifdef __cplusplus
}
#endif

#endif	/* _RepositoryDelegation_H_ */
#include <asn_internal.h>
