/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TrustPinningModule"
 * 	found in "TrustPinningModule.asn1"
 */

#include "RepositoryDelegation.h"

static asn_TYPE_member_t asn_MBR_RepositoryDelegation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RepositoryDelegation, numberOfPaths),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Length,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfPaths"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RepositoryDelegation, paths),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Paths,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"paths"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RepositoryDelegation, numberOfRepositories),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Length,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfRepositories"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RepositoryDelegation, repositories),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RepositoryNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"repositories"
		},
	{ ATF_POINTER, 1, offsetof(struct RepositoryDelegation, terminating),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"terminating"
		},
};
static ber_tlv_tag_t asn_DEF_RepositoryDelegation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RepositoryDelegation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* numberOfPaths at 38 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* paths at 39 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* numberOfRepositories at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* repositories at 42 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* terminating at 44 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RepositoryDelegation_specs_1 = {
	sizeof(struct RepositoryDelegation),
	offsetof(struct RepositoryDelegation, _asn_ctx),
	asn_MAP_RepositoryDelegation_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RepositoryDelegation = {
	"RepositoryDelegation",
	"RepositoryDelegation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RepositoryDelegation_tags_1,
	sizeof(asn_DEF_RepositoryDelegation_tags_1)
		/sizeof(asn_DEF_RepositoryDelegation_tags_1[0]), /* 1 */
	asn_DEF_RepositoryDelegation_tags_1,	/* Same as above */
	sizeof(asn_DEF_RepositoryDelegation_tags_1)
		/sizeof(asn_DEF_RepositoryDelegation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RepositoryDelegation_1,
	5,	/* Elements count */
	&asn_SPC_RepositoryDelegation_specs_1	/* Additional specs */
};

