/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TimeServerModule"
 * 	found in "TimeServerModule.asn1"
 */

#ifndef	_SequenceOfNonces_H_
#define	_SequenceOfNonces_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Length.h"
#include "Nonces.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceOfNonces */
typedef struct SequenceOfNonces {
	Length_t	 numberOfNonces;
	Nonces_t	 nonces;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfNonces_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfNonces;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceOfNonces_H_ */
#include <asn_internal.h>
