/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CommonModule"
 * 	found in "CommonModule.asn1"
 */

#ifndef	_Signature_H_
#define	_Signature_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Keyid.h"
#include "SignatureMethod.h"
#include "Hash.h"
#include "HexString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Signature */
typedef struct Signature {
	Keyid_t	 keyid;
	SignatureMethod_t	 method;
	Hash_t	 hash;
	HexString_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Signature;

#ifdef __cplusplus
}
#endif

#endif	/* _Signature_H_ */
#include <asn_internal.h>
