/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#ifndef	_TargetsDelegations_H_
#define	_TargetsDelegations_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Length.h"
#include "PublicKeys.h"
#include "DelegatedTargetsRoles.h"
#include "PrioritizedPathsToRoles.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TargetsDelegations */
typedef struct TargetsDelegations {
	Length_t	 numberOfKeys;
	PublicKeys_t	 keys;
	Length_t	 numberOfRoles;
	DelegatedTargetsRoles_t	 roles;
	Length_t	 numberOfPrioritizedPathsToRoles;
	PrioritizedPathsToRoles_t	 prioritizedPathsToRoles;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetsDelegations_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetsDelegations;

#ifdef __cplusplus
}
#endif

#endif	/* _TargetsDelegations_H_ */
#include <asn_internal.h>
