/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TrustPinningModule"
 * 	found in "TrustPinningModule.asn1"
 */

#ifndef	_TrustPinning_H_
#define	_TrustPinning_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Length.h"
#include "Repositories.h"
#include "RepositoryDelegations.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TrustPinning */
typedef struct TrustPinning {
	Length_t	 numberOfRepositories;
	Repositories_t	 repositories;
	Length_t	 numberOfDelegations;
	RepositoryDelegations_t	 delegations;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrustPinning_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrustPinning;

#ifdef __cplusplus
}
#endif

#endif	/* _TrustPinning_H_ */
#include <asn_internal.h>
