/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CommonModule"
 * 	found in "CommonModule.asn1"
 */

#ifndef	_Base64String_H_
#define	_Base64String_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Base64String */
typedef VisibleString_t	 Base64String_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Base64String;
asn_struct_free_f Base64String_free;
asn_struct_print_f Base64String_print;
asn_constr_check_f Base64String_constraint;
ber_type_decoder_f Base64String_decode_ber;
der_type_encoder_f Base64String_encode_der;
xer_type_decoder_f Base64String_decode_xer;
xer_type_encoder_f Base64String_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Base64String_H_ */
#include <asn_internal.h>
