/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MetadataModule"
 * 	found in "MetadataModule.asn1"
 */

#ifndef	_Metadata_H_
#define	_Metadata_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Signed.h"
#include "Signatures.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Metadata */
typedef struct Metadata {
	Signed_t	 Signed;
	Signatures_t	 signatures;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Metadata_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Metadata;

#ifdef __cplusplus
}
#endif

#endif	/* _Metadata_H_ */
#include <asn_internal.h>
