/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "TargetsModule"
 * 	found in "TargetsModule.asn1"
 */

#ifndef	_Target_H_
#define	_Target_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Filename.h"
#include "Length.h"
#include "Hashes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Target */
typedef struct Target {
	Filename_t	 filename;
	Length_t	 length;
	Hashes_t	 hashes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Target_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Target;

#ifdef __cplusplus
}
#endif

#endif	/* _Target_H_ */
#include <asn_internal.h>
