/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "RootModule"
 * 	found in "RootModule.asn1"
 */

#include "TopLevelRoles.h"

static asn_TYPE_member_t asn_MBR_TopLevelRoles_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRoles, role),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoleType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"role"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRoles, url),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"url"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRoles, keyids),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Keyids,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyids"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRoles, threshold),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Threshold,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"threshold"
		},
};
static ber_tlv_tag_t asn_DEF_TopLevelRoles_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TopLevelRoles_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* role at 14 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* url at 16 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* keyids at 17 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* threshold at 18 */
};
static asn_SEQUENCE_specifics_t asn_SPC_TopLevelRoles_specs_1 = {
	sizeof(struct TopLevelRoles),
	offsetof(struct TopLevelRoles, _asn_ctx),
	asn_MAP_TopLevelRoles_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TopLevelRoles = {
	"TopLevelRoles",
	"TopLevelRoles",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TopLevelRoles_tags_1,
	sizeof(asn_DEF_TopLevelRoles_tags_1)
		/sizeof(asn_DEF_TopLevelRoles_tags_1[0]), /* 1 */
	asn_DEF_TopLevelRoles_tags_1,	/* Same as above */
	sizeof(asn_DEF_TopLevelRoles_tags_1)
		/sizeof(asn_DEF_TopLevelRoles_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TopLevelRoles_1,
	4,	/* Elements count */
	&asn_SPC_TopLevelRoles_specs_1	/* Additional specs */
};

