/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "RootModule"
 * 	found in "RootModule.asn1"
 */

#ifndef	_TopLevelRoles_H_
#define	_TopLevelRoles_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RoleType.h"
#include <VisibleString.h>
#include "Keyids.h"
#include "Threshold.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TopLevelRoles */
typedef struct TopLevelRoles {
	RoleType_t	 role;
	VisibleString_t	 url;
	Keyids_t	 keyids;
	Threshold_t	 threshold;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TopLevelRoles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TopLevelRoles;

#ifdef __cplusplus
}
#endif

#endif	/* _TopLevelRoles_H_ */
#include <asn_internal.h>
